FLAIRS = {
    None: {'club': None, 'country': None, 'league': None},
    '2015poola': {'club': None, 'country': None, 'league': None},
    '2015poolb': {'club': None, 'country': None, 'league': None},
    '2015poolc': {'club': None, 'country': None, 'league': None},
    '2015poold': {'club': None, 'country': None, 'league': None},
    '2020murder1': {'club': None, 'country': None, 'league': None},
    '2020tokyo1': {'club': None, 'country': None, 'league': None},
    ':Arrows:': {
        'club': 'toronto arrows', 'country': 'canada', 'league': 'mlr'},
    ':British_and_Irish_Lions:': {
        'club': None, 'country': None, 'league': None},
    ':Elite:': {
        'club': 'austin gilgronis', 'country': 'usa', 'league': 'mlr'},
    ':England-flag:': {
        'club': None, 'country': 'england', 'league': None},
    ':Fiji-flag:': {'club': None, 'country': 'fiji', 'league': None},
    ':Japan-flag:': {'club': None, 'country': 'japan', 'league': None},
    ':Legion:': {
        'club': 'san diego legion', 'country': 'usa', 'league': 'mlr'},
    ':MLR:': {'club': None, 'country': 'usa', 'league': 'mlr'},
    ':NolaGold:': {
        'club': 'nola gold', 'country': 'usa', 'league': 'mlr'},
    ':Russia-flag:': {
        'club': None, 'country': 'russia', 'league': None},
    ':Sabercats:': {
        'club': 'houston sabercats', 'country': 'usa', 'league': 'mlr'},
    ':Seawolves:': {
        'club': 'seattle seawolves', 'country': 'usa', 'league': 'mlr'},
    ':South-Africa:': {'club': None, 'country': 'south africa', 'league': None},
    ':SouthAfrica-flag:': {
        'club': None, 'country': 'south africa', 'league': None},
    ':Tonga-fag:': {'club': None, 'country': 'tonga', 'league': None},
    ':US-flag:': {'club': None, 'country': 'usa', 'league': None},
    ':Uruguay-logo:': {
        'club': None, 'country': 'uruguay', 'league': None},
    ':WC2019:': {
        'club': None, 'country': None, 'league': None},
    ':Warriors:': {
        'club': 'utah warriors', 'country': 'usa', 'league': 'mlr'},
    ':Webp:': {
        'club': 'rugby united new york', 'country': 'usa', 'league': 'mlr'},
    ':argentina-flag:': {'club': None, 'country': 'argentina', 'league': None},
    ':barbarians-logo:': {'club': None, 'country': None, 'league': None},
    ':georgia-flag:': {'club': None, 'country': 'georgia', 'league': None},
    ':germany-logo:': {'club': None, 'country': 'germany', 'league': None},
    ':greece-flag:': {'club': None, 'country': 'greece', 'league': None},
    ':ireland-flag:': {'club': None, 'country': 'ireland', 'league': None},
    ':italy-flag:': {'club': None, 'country': 'italy', 'league': None},
    ':kenya-flag:': {'club': None, 'country': 'kenya', 'league': None},
    ':logo-glendaleraptors:': {'club': 'colorado raptors',
                               'country': 'usa',
                               'league': 'mlr'},
    ':mitre10-logo:': {'club': None,
                       'country': 'new zealand',
                       'league': 'mitre 10'},
    ':namibia-flag:': {'club': None, 'country': 'namibia', 'league': None},
    ':newZealand-flag:': {'club': None, 'country': 'new zealand', 'league': None},
    ':nrc-logo:': {'club': None, 'country': 'australia', 'league': 'nrc'},
    ':portugal-flag:': {'club': None, 'country': 'portugal', 'league': None},
    ':premiereship-logo:': {'club': None,
                            'country': 'england',
                            'league': 'premiership'},
    ':pro14-logo:': {'club': None, 'country': None, 'league': 'pro14'},
    ':romania-logo:': {'club': None, 'country': 'romania', 'league': None},
    ':samoa-flag:': {'club': None, 'country': 'samoa', 'league': None},
    ':scotland-flag:': {'club': None, 'country': 'scotland', 'league': None},
    ':spain-flag:': {'club': None, 'country': 'spain', 'league': None},
    ':super-logo:': {'club': None, 'country': None, 'league': 'super rugby'},
    ':top14-logo:': {'club': None, 'country': 'france', 'league': 'top14'},
    ':uruguay-flag:': {'club': None, 'country': 'uruguay', 'league': None},
    'Argentina': {'club': None, 'country': 'argentina', 'league': None},
    'Ireland': {'club': None, 'country': 'ireland', 'league': None},
    'Sweden': {'club': None, 'country': 'sweden', 'league': None},
    'albi': {'club': 'sc albi', 'country': 'france', 'league': 'federale 1'},
    'algeria': {'club': None, 'country': 'algeria', 'league': None},
    'all-blacks': {'club': None, 'country': 'new zealand', 'league': None},
    'arc': {'club': None, 'country': None, 'league': 'arc'},
    'argentina': {'club': None, 'country': 'argentina', 'league': None},
    'armchair': {'club': None, 'country': None, 'league': None},
    'auch-gers': {'club': 'auch gers', 'country': 'france', 'league': None},
    'auckland': {'club': 'auckland',
                 'country': 'new zealand',
                 'league': 'mitre 10'},
    'australia': {'club': None, 'country': 'australia', 'league': None},
    'austria': {'club': None, 'country': 'austria', 'league': None},
    'aviron': {'club': 'bayonne', 'country': 'france', 'league': 'top14'},
    'baabaas': {'club': None, 'country': None, 'league': None},
    'ball': {'club': None, 'country': None, 'league': None},
    'bath': {'club': 'bath', 'country': 'england', 'league': 'premiership'},
    'bedford': {'club': 'bedford blues',
                'country': 'england',
                'league': 'championship'},
    'biarritz': {'club': 'biarritz', 'country': 'france', 'league': 'top14'},
    'blues': {'club': 'blues', 'country': 'new zealand', 'league': 'super rugby'},
    'bordeux': {'club': 'bordeaux', 'country': 'france', 'league': 'top14'},
    'bourgoin': {'club': 'cs bourgoin-jallieu',
                 'country': 'france',
                 'league': 'federale 1'},
    'brazil': {'club': None, 'country': 'brazil', 'league': None},
    'bridgend-ravens': {'club': 'bridgend ravens',
                        'country': 'wales',
                        'league': 'welsh premiership'},
    'bristol': {'club': 'bristol', 'country': 'england', 'league': 'premiership'},
    'british-irish-lions': {'club': None, 'country': None, 'league': None},
    'brive': {'club': 'ca brive', 'country': 'france', 'league': 'top14'},
    'brumbles': {'club': 'act brumbies',
                 'country': 'australia',
                 'league': 'super rugby'},
    'bulls': {'club': 'bulls', 'country': 'south africa', 'league': 'super rugby'},
    'cambodia': {'club': None, 'country': 'cambodia', 'league': None},
    'canada': {'club': None, 'country': 'canada', 'league': None},
    'cardiff-blues': {'club': 'cardiff blues',
                      'country': 'wales',
                      'league': 'pro14'},
    'castres': {'club': 'castres', 'country': 'france', 'league': 'top14'},
    'cheetahs': {'club': 'cheetahs', 'country': 'south africa', 'league': 'pro14'},
    'chile': {'club': None, 'country': 'chile', 'league': None},
    'clermont-auvergne': {'club': 'clermont auvergne',
                          'country': 'france',
                          'league': 'top14'},
    'connacht': {'club': 'connacht', 'country': 'ireland', 'league': 'pro14'},
    'crusaders': {'club': 'crusaders',
                  'country': 'new zealand',
                  'league': 'super rugby'},
    'dax': {'club': 'us dax', 'country': 'france', 'league': 'prod2'},
    'edinburgh': {'club': 'edinburgh', 'country': 'scotland', 'league': 'pro14'},
    'eight': {'club': None, 'country': None, 'league': None},
    'eleven': {'club': None, 'country': None, 'league': None},
    'embra2': {'club': 'edinburgh', 'country': 'scotland', 'league': 'pro14'},
    'england': {'club': None, 'country': 'england', 'league': None},
    'exeter-chiefs': {'club': 'exeter chiefs',
                      'country': 'england',
                      'league': 'premiership'},
    'fifteen': {'club': None, 'country': None, 'league': None},
    'fiji': {'club': None, 'country': 'fiji', 'league': None},
    'five': {'club': None, 'country': None, 'league': None},
    'flair-gloucester': {'club': 'gloucester',
                         'country': 'england',
                         'league': 'premiership'},
    'flair-harlequins': {'club': 'harlequins',
                         'country': 'england',
                         'league': 'premiership'},
    'flair-highlanders': {'club': 'highlanders',
                          'country': 'new zealand',
                          'league': 'super rugby'},
    'flair-hurricanes': {'club': 'hurricanes',
                         'country': 'new zealand',
                         'league': 'super rugby'},
    'flair-ireland': {'club': None, 'country': 'ireland', 'league': None},
    'flair-leeds': {'club': 'leeds',
                    'country': 'england',
                    'league': 'championship'},
    'flalr-glasgow': {'club': 'glasgow warriors',
                      'country': 'scotland',
                      'league': 'pro14'},
    'four': {'club': None, 'country': None, 'league': None},
    'fourteen': {'club': None, 'country': None, 'league': None},
    'france': {'club': None, 'country': 'france', 'league': None},
    'georgia': {'club': None, 'country': 'georgia', 'league': None},
    'germany': {'club': None, 'country': 'germany', 'league': None},
    'glasgow': {'club': 'glasgow warriors',
                'country': 'england',
                'league': 'pro14'},
    'gloucester': {'club': 'gloucester',
                   'country': 'england',
                   'league': 'premiership'},
    'greece': {'club': None, 'country': 'greece', 'league': None},
    'grenoble': {'club': 'grenoble', 'country': 'france', 'league': 'top14'},
    'harlequins': {'club': 'harlequins',
                   'country': 'england',
                   'league': 'premiership'},
    'highlanders': {'club': 'highlanders',
                    'country': 'new zealand',
                    'league': 'super rugby'},
    'hongkong': {'club': None, 'country': 'hong kong', 'league': None},
    'horowhenua': {'club': 'horowhenua', 'country': 'new zealand', 'league': None},
    'hurricanes': {'club': 'hurricanes',
                   'country': 'new zealand',
                   'league': 'super rugby'},
    'iceland': {'club': None, 'country': 'iceland', 'league': None},
    'ireland': {'club': None, 'country': 'ireland', 'league': None},
    'italy': {'club': None, 'country': 'italy', 'league': None},
    'j19a': {'club': None, 'country': None, 'league': None},
    'j19b': {'club': None, 'country': None, 'league': None},
    'j19c': {'club': None, 'country': None, 'league': None},
    'j19d': {'club': None, 'country': None, 'league': None},
    'jaguares': {'club': 'jaguares',
                 'country': 'argentina',
                 'league': 'super rugby'},
    'japan': {'club': None, 'country': 'japan', 'league': None},
    'kenya': {'club': None, 'country': 'kenya', 'league': None},
    'larochelle': {'club': 'la rochelle', 'country': 'france', 'league': 'top14'},
    'leicester': {'club': 'leicester tigers',
                  'country': 'england',
                  'league': 'premiership'},
    'leinster': {'club': 'leinster', 'country': 'ireland', 'league': 'pro14'},
    'lions': {'club': 'lions', 'country': 'south africa', 'league': 'super rugby'},
    'llanelli-scarlets': {'club': 'llanelli scarlets',
                          'country': 'wales',
                          'league': 'pro14'},
    'london-irish': {'club': 'london irish',
                     'country': None,
                     'league': 'premiership'},
    'london-welsh': {'club': 'london welsh', 'country': 'england', 'league': None},
    'lyon': {'club': 'lyon', 'country': 'france', 'league': 'top14'},
    'malawi7s': {'club': 'malawi 7s', 'country': 'malawi', 'league': None},
    'manawatu': {'club': 'manawatu', 'country': 'new zealand', 'league': None},
    'manukau': {'club': 'counties manukau',
                'country': 'new zealand',
                'league': 'mitre 10'},
    'melbourne-rebels': {'club': 'melbourne rebels',
                         'country': 'australia',
                         'league': 'super rugby'},
    'moldova': {'club': None, 'country': 'moldova', 'league': None},
    'montauban': {'club': 'us montauban', 'country': 'france', 'league': 'prod2'},
    'montpellier': {'club': 'montpellier', 'country': 'france', 'league': 'top14'},
    'munster': {'club': 'munster', 'country': 'ireland', 'league': 'pro14'},
    'namibia': {'club': None, 'country': 'namibia', 'league': None},
    'nejacks': {'club': 'new england free jacks',
                'country': 'usa',
                'league': 'mlr'},
    'netherlands': {'club': None, 'country': 'netherlands', 'league': None},
    'newcastle': {'club': 'newcastle falcons',
                  'country': 'england',
                  'league': 'premiership'},
    'newport': {'club': 'dragons', 'country': 'wales', 'league': 'pro14'},
    'nine': {'club': None, 'country': None, 'league': None},
    'north-harbour': {'club': 'north harbour',
                      'country': 'new zealand',
                      'league': 'mitre 10'},
    'northampton': {'club': 'northampton saints',
                    'country': 'england',
                    'league': 'premiership'},
    'northland': {'club': 'northland', 'country': 'new zealand', 'league': None},
    'nzcant': {'club': 'canterbury',
               'country': 'new zealand',
               'league': 'mitre 10'},
    'one': {'club': None, 'country': None, 'league': None},
    'ontario': {'club': 'ontario blues', 'country': 'canada', 'league': 'arc'},
    'ontario-blues': {'club': 'ontario blues',
                      'country': 'canada',
                      'league': 'arc'},
    'ospreys': {'club': 'ospreys', 'country': 'wales', 'league': 'pro14'},
    'otago': {'club': 'otago razorbacks',
              'country': 'new zealand',
              'league': 'mitre 10'},
    'paris': {'club': 'stade francais paris',
              'country': 'france',
              'league': 'top14'},
    'pau': {'club': 'pau', 'country': 'france', 'league': 'top14'},
    'perpignan': {'club': 'perpignan', 'country': 'france', 'league': 'top14'},
    'poland': {'club': None, 'country': 'poland', 'league': None},
    'pontypridd': {'club': 'pontypridd',
                   'country': 'wales',
                   'league': 'welsh premiership'},
    'portugal': {'club': None, 'country': 'portugal', 'league': None},
    'racing-metro': {'club': 'racing 92', 'country': 'france', 'league': 'top14'},
    'reds': {'club': 'queensland reds',
             'country': 'australia',
             'league': 'super rugby'},
    'ref': {'club': None, 'country': None, 'league': None},
    'rgc1404': {'club': 'rgc1404',
                'country': 'wales',
                'league': 'welsh premiership'},
    'romania': {'club': None, 'country': 'romania', 'league': None},
    'rugby-champ': {'club': None, 'country': None, 'league': None},
    'russia': {'club': None, 'country': 'russia', 'league': None},
    'sale': {'club': 'sale sharks', 'country': 'england', 'league': 'premiership'},
    'samoa': {'club': None, 'country': 'samoa', 'league': None},
    'sanzar': {'club': None, 'country': None, 'league': None},
    'saracens': {'club': 'saracens',
                 'country': 'england',
                 'league': 'premiership'},
    'scotland': {'club': None, 'country': 'scotland', 'league': None},
    'serpientes': {'club': None, 'country': 'mexico', 'league': None},
    'seven': {'club': None, 'country': None, 'league': None},
    'sharks': {'club': 'sharks',
               'country': 'south africa',
               'league': 'super rugby'},
    'singapore': {'club': None, 'country': 'singapore', 'league': None},
    'six': {'club': None, 'country': None, 'league': None},
    'south-africa': {'club': None, 'country': 'south africa', 'league': None},
    'southern-kings': {'club': 'southern kings',
                       'country': 'south africa',
                       'league': 'pro14'},
    'southland': {'club': 'southland stags',
                  'country': 'new zealand',
                  'league': 'mitre 10'},
    'spain': {'club': None, 'country': 'spain', 'league': None},
    'squidge': {'club': None, 'country': None, 'league': None},
    'stormers': {'club': 'stormers',
                 'country': 'south africa',
                 'league': 'super rugby'},
    'sudamerica': {'club': None, 'country': None, 'league': None},
    'sunwolves': {'club': 'sunwolves',
                  'country': 'japan',
                  'league': 'super rugby'},
    'swiss': {'club': None, 'country': 'switzerland', 'league': None},
    'tanzania': {'club': None, 'country': 'tanzania', 'league': None},
    'taranaki': {'club': 'taranaki bulls',
                 'country': 'new zealand',
                 'league': 'mitre 10'},
    'tasman-makos': {'club': 'tasman makos',
                     'country': 'new zealand',
                     'league': 'mitre 10'},
    'teamgb2': {'club': None, 'country': None, 'league': None},
    'ten': {'club': None, 'country': None, 'league': None},
    'thailand': {'club': None, 'country': 'thailand', 'league': None},
    'thirteen': {'club': None, 'country': None, 'league': None},
    'three': {'club': None, 'country': None, 'league': None},
    'tiverton': {'club': 'tiverton rfc', 'country': 'england', 'league': None},
    'tonga': {'club': None, 'country': 'tonga', 'league': None},
    'topleague': {'club': None, 'country': 'japan', 'league': 'top league'},
    'toulon': {'club': 'toulon', 'country': 'france', 'league': 'top14'},
    'toulousain': {'club': 'toulouse', 'country': 'france', 'league': 'top14'},
    'treviso': {'club': 'treviso', 'country': 'italy', 'league': 'pro14'},
    'twelve': {'club': None, 'country': None, 'league': None},
    'two': {'club': None, 'country': None, 'league': None},
    'ukraine': {'club': None, 'country': 'ukraine', 'league': None},
    'ulster': {'club': 'ulster', 'country': 'ireland', 'league': 'pro14'},
    'uruguay': {'club': None, 'country': 'uruguay', 'league': None},
    'usa': {'club': None, 'country': 'usa', 'league': None},
    'voyageurs': {'club': 'voyageurs', 'country': 'canada', 'league': None},
    'waikato': {'club': 'waikato', 'country': 'new zealand', 'league': 'mitre 10'},
    'waikato-chiefs': {'club': 'chiefs',
                       'country': 'new zealand',
                       'league': 'super rugby'},
    'wales': {'club': None, 'country': 'wales', 'league': None},
    'waratahs': {'club': 'nsw waratahs',
                 'country': 'australia',
                 'league': 'super rugby'},
    'wasps': {'club': 'wasps', 'country': 'england', 'league': 'premiership'},
    'weegie2': {'club': 'glasgow warriors',
                'country': 'scotland',
                'league': 'pro14'},
    'wellington': {'club': 'wellington lions',
                   'country': 'new zealand',
                   'league': 'mitre 10'},
    'western-force': {'club': 'western force',
                      'country': 'australia',
                      'league': None},
    'worcester': {'club': 'worcester warriors',
                  'country': 'england',
                  'league': 'premiership'},
    'wrcarg': {'club': None, 'country': 'argentina', 'league': None},
    'wrcaus': {'club': None, 'country': 'australia', 'league': None},
    'wrccan': {'club': None, 'country': 'canada', 'league': None},
    'wrceng': {'club': None, 'country': 'england', 'league': None},
    'wrcfij': {'club': None, 'country': 'fiji', 'league': None},
    'wrcfra': {'club': None, 'country': 'france', 'league': None},
    'wrcfra2': {'club': None, 'country': 'france', 'league': None},
    'wrcgeo': {'club': None, 'country': 'georgia', 'league': None},
    'wrcire': {'club': None, 'country': 'ireland', 'league': None},
    'wrcita': {'club': None, 'country': 'italy', 'league': None},
    'wrcjap': {'club': None, 'country': 'japan', 'league': None},
    'wrcnam': {'club': None, 'country': 'namibia', 'league': None},
    'wrcnzl': {'club': None, 'country': 'new zealand', 'league': None},
    'wrcrom': {'club': None, 'country': 'romania', 'league': None},
    'wrcrsa': {'club': None, 'country': 'south africa', 'league': None},
    'wrcrus': {'club': None, 'country': 'russia', 'league': None},
    'wrcsam': {'club': None, 'country': 'samoa', 'league': None},
    'wrcsco': {'club': None, 'country': 'scotland', 'league': None},
    'wrcton': {'club': None, 'country': 'tonga', 'league': None},
    'wrcuru': {'club': None, 'country': 'uruguay', 'league': None},
    'wrcusa': {'club': None, 'country': 'usa', 'league': None},
    'wrcwal': {'club': None, 'country': 'wales', 'league': None},
    'wrcwr': {'club': None, 'country': None, 'league': None},
    'zebre': {'club': 'zebre', 'country': 'italy', 'league': 'pro14'}
}

CUSTOM_PROFANITIES = {
  'arse/ass': [
    'ahole',
    'arse',
    'arseface',
    'arseh0le',
    'arseh0lez',
    'arsehole',
    'arseholes',
    'arseholz',
    'arsemonkey',
    'arserammer',
    'arsewipe',
    'ash0le',
    'asholes',
    'ass',
    'assface',
    'assh0le',
    'assh0lez',
    'asshole',
    'assholes',
    'assholz',
    'asswipe',
    'azzhole',
  ],
  'bitch': [
    'b17ch',
    'b1tch',
    'bi7ch',
    'biatch',
    'bich',
    'bitch',
  ],
  'bastard' : [
    'bassterds',
    'bastard',
    'bastardz',
    'basterds',
    'basterdz',
  ],
  'bollocks': [
    'bollock',
    'bollocks',
  ],
  'bugger': [
    'bugger',
  ],
  'cunt': [
    'cnts',
    'cntz',
    'cunt',
    'cuntz',
    'cuntwipe',
    'cuntwipes',
    'cunty',
    'kunt',
    'kuntz',
  ],
  'cock': [
    'c0ck',
    'c0k',
    'cock',
    'cockhead',
    'cockheads',
    'cocksucker',
    'cocksuckers',
  ],
  'carpetmuncher': [
    'carpetmuncher',
  ],
  'crap': [
    'crap',
    'crappy',
  ],
  'dick': [
    'dick',
    'dickhead',
    'dickheads',
  ],
  'fag/faggot': [
    'fag',
    'fag1t',
    'faget',
    'fagg1t',
    'faggit',
    'faggot',
    'fagit',
    'fagz',
  ],
  'fuck': [
    'fuck',
    'fucka',
    'fucker',
    'fuckers',
    'fuckin',
    'fucking',
    'fuckhead',
    'fuckheads',
    'fuckwit',
    'fuckwits',
    'fcuk',
    'fukah',
    'fuken',
    'fuker',
    'fukin',
    'fukka',
    'fukkah',
    'fukken',
    'fukker',
    'fukkin',
  ],
  'fudgepacker': [
    'fudgepacker'
  ],
  'knob': [
    'knob',
    'knobhead',
    'knobheads',
    'knobz',
  ],
  'motherfucker': [
    'mothafucker',
    'mothafuker',
    'mothafukkah',
    'mothafukker',
    'motherfucker',
    'motherfuckers',
    'motherfukah',
    'motherfuker',
    'motherfukkah',
    'motherfukker',
    'muthafucker',
    'muthafukah',
    'muthafuker',
    'muthafukkah',
    'muthafukker',
  ],
  'prick': [
    'pr1ck',
    'pr1k',
    'prick',
  ],
  'pussy': [
    'pussy',
  ],
  'shit': [
    'shit',
    'shitt',
    'shitter',
    'shitty',
    'shithead',
    'shitheads',
    'shite',
    'shity',
    'shitz',
    'sh1ter',
    'sh1ts',
    'sh1tter',
    'sh1tz',
    'bullshit',
  ],
  'wank': [
    'wank',
    'wanker',
    'wankers',
    'wankstain',
    'wankstains',
  ]
}
